from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

p = ROOT / 'reader-speed-playback-ui.js'
s = p.read_text(encoding='utf-8')

repls = []
repls.append((
"""        root && root.ReaderAssetRendererV2,\n    );\n    if (typeof module === 'object' && module.exports) module.exports = api;\n    if (root) root.ReaderSpeedPlaybackUI = api;\n})(typeof globalThis !== 'undefined' ? globalThis : this, function (ReaderUI, Adapter, PlaybackModule, Assets) {\n""",
"""        root && root.ReaderAssetRendererV2,\n        root && root.ReaderTrainingSessionClock,\n    );\n    if (typeof module === 'object' && module.exports) module.exports = api;\n    if (root) root.ReaderSpeedPlaybackUI = api;\n})(typeof globalThis !== 'undefined' ? globalThis : this, function (ReaderUI, Adapter, PlaybackModule, Assets, TrainingClockModule) {\n"""))
repls.append((
"""            Assets = Assets || require('./reader-assets.js');\n        }\n        if (!ReaderUI || !Adapter || !PlaybackModule || !Assets) throw new Error('Reader v2 playback dependencies are required');\n        return { ReaderUI, Adapter, PlaybackModule, Assets };\n""",
"""            Assets = Assets || require('./reader-assets.js');\n            TrainingClockModule = TrainingClockModule || require('./training-session-clock.js');\n        }\n        if (!ReaderUI || !Adapter || !PlaybackModule || !Assets || !TrainingClockModule) throw new Error('Reader v2 playback dependencies are required');\n        return { ReaderUI, Adapter, PlaybackModule, Assets, TrainingClockModule };\n"""))
repls.append((
"""            this.assets = options.assets || deps.Assets;\n            this.playback = options.playback || new deps.PlaybackModule.PlaybackController({\n                scheduler: options.scheduler,\n                onChange: (snapshot) => this.renderSnapshot(snapshot),\n            });\n            this.bound = false;\n            this.openBookPatched = false;\n""",
"""            this.assets = options.assets || deps.Assets;\n            this.playback = options.playback || new deps.PlaybackModule.PlaybackController({\n                scheduler: options.scheduler,\n                onChange: (snapshot) => this.renderSnapshot(snapshot),\n            });\n            this.trainingClock = options.trainingClock || new deps.TrainingClockModule.TrainingSessionClock({\n                now: options.trainingNow,\n            });\n            this.trainingPaused = false;\n            this.comprehensionPaused = false;\n            this.resumePlaybackAfterTrainingPause = false;\n            const view = this.document?.defaultView || null;\n            this.setIntervalFn = options.setIntervalFn || (view?.setInterval ? view.setInterval.bind(view) : null);\n            this.clearIntervalFn = options.clearIntervalFn || (view?.clearInterval ? view.clearInterval.bind(view) : null);\n            this.trainingTicker = null;\n            this.bound = false;\n            this.openBookPatched = false;\n"""))
repls.append((
"""        element(id) {\n            return this.document ? this.document.getElementById(id) : null;\n        }\n\n        isReaderActive() {\n""",
"""        element(id) {\n            return this.document ? this.document.getElementById(id) : null;\n        }\n\n        formatElapsed(ms) {\n            const totalSeconds = Math.max(0, Math.floor(Number(ms || 0) / 1000));\n            const minutes = Math.floor(totalSeconds / 60);\n            const seconds = totalSeconds % 60;\n            return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;\n        }\n\n        updateTrainingTime() {\n            const target = this.element('readingTime');\n            if (target) target.textContent = this.formatElapsed(this.trainingClock?.elapsedMs?.() || 0);\n        }\n\n        startTrainingTicker() {\n            this.stopTrainingTicker();\n            this.updateTrainingTime();\n            if (!this.setIntervalFn) return;\n            this.trainingTicker = this.setIntervalFn(() => this.updateTrainingTime(), 250);\n        }\n\n        stopTrainingTicker() {\n            if (this.trainingTicker !== null && this.clearIntervalFn) this.clearIntervalFn(this.trainingTicker);\n            this.trainingTicker = null;\n        }\n\n        beginTrainingSession() {\n            this.trainingPaused = false;\n            this.comprehensionPaused = false;\n            this.resumePlaybackAfterTrainingPause = false;\n            this.trainingClock.start();\n            this.startTrainingTicker();\n        }\n\n        isReaderActive() {\n"""))
repls.append((
"""        async start() {\n            if (!this.isReaderActive()) return false;\n            await this.ensureAllContent();\n            this.refreshFrames();\n            this.applyVisualSettings();\n            return this.playback.play();\n        }\n\n        stop() {\n            this.persistResume();\n            this.playback.stop();\n            this.showReaderSurface();\n        }\n\n        togglePause() {\n            if (!this.isReaderActive()) return false;\n            if (this.playback.state === 'playing') return this.playback.pause();\n            if (this.playback.state === 'paused') return this.playback.resume();\n            if (this.playback.state === 'manual') return this.playback.continueManual();\n            return false;\n        }\n""",
"""        async start() {\n            if (!this.isReaderActive()) return false;\n            await this.ensureAllContent();\n            this.refreshFrames();\n            this.applyVisualSettings();\n            this.beginTrainingSession();\n            const started = this.playback.play();\n            if (!started) {\n                this.trainingClock.stop();\n                this.stopTrainingTicker();\n            }\n            return started;\n        }\n\n        stop() {\n            this.persistResume();\n            this.trainingClock.stop();\n            this.stopTrainingTicker();\n            this.trainingPaused = false;\n            this.comprehensionPaused = false;\n            this.resumePlaybackAfterTrainingPause = false;\n            this.updateTrainingTime();\n            this.playback.stop();\n            this.showReaderSurface();\n        }\n\n        toggleComprehensionPause() {\n            if (!this.isReaderActive() || this.trainingPaused) return false;\n            if (this.playback.state === 'playing') {\n                this.comprehensionPaused = true;\n                return this.playback.pause();\n            }\n            if (this.playback.state === 'paused' && this.comprehensionPaused) {\n                this.comprehensionPaused = false;\n                return this.playback.resume();\n            }\n            return false;\n        }\n\n        toggleTrainingPause() {\n            if (!this.isReaderActive() || !ACTIVE_STATES.has(this.playback.state)) return false;\n            if (!this.trainingPaused) {\n                this.trainingPaused = true;\n                this.resumePlaybackAfterTrainingPause = this.playback.state === 'playing';\n                this.trainingClock.pause();\n                if (this.resumePlaybackAfterTrainingPause) this.playback.pause();\n                else {\n                    this.updateTrainingTime();\n                    this.updateControls();\n                }\n                return true;\n            }\n\n            this.trainingPaused = false;\n            this.trainingClock.resume();\n            const shouldResumePlayback = this.resumePlaybackAfterTrainingPause;\n            this.resumePlaybackAfterTrainingPause = false;\n            if (shouldResumePlayback && this.playback.state === 'paused') {\n                this.comprehensionPaused = false;\n                return this.playback.resume();\n            }\n            this.updateTrainingTime();\n            this.updateControls();\n            return true;\n        }\n\n        togglePause() {\n            return this.toggleTrainingPause();\n        }\n\n        continueManual() {\n            if (this.trainingPaused || this.playback.state !== 'manual') return false;\n            return this.playback.continueManual();\n        }\n"""))
repls.append((
"""                this.playback.continueManual();\n""",
"""                this.continueManual();\n"""))
repls.append((
"""        stateLabel(snapshot) {\n            if (!snapshot.frame_count) return '无可播放内容';\n            if (snapshot.state === 'playing') return '播放中';\n            if (snapshot.state === 'paused') return '已暂停';\n            if (snapshot.state === 'manual') return '等待继续';\n            if (snapshot.state === 'completed') return '已完成';\n            return '未开始';\n        }\n""",
"""        stateLabel(snapshot) {\n            if (!snapshot.frame_count) return '无可播放内容';\n            if (this.trainingPaused) return '训练已暂停';\n            if (snapshot.state === 'playing') return '播放中';\n            if (snapshot.state === 'paused' && this.comprehensionPaused) return '理解中 · 计时继续';\n            if (snapshot.state === 'paused') return '自动播放已暂停';\n            if (snapshot.state === 'manual') return '阅读图表/公式 · 计时继续';\n            if (snapshot.state === 'completed') return '已完成';\n            return '未开始';\n        }\n"""))
repls.append((
"""        renderSnapshot(snapshot) {\n            const current = this.element('currentPos');\n""",
"""        renderSnapshot(snapshot) {\n            if (snapshot.state === 'completed') {\n                this.trainingClock.stop();\n                this.stopTrainingTicker();\n                this.trainingPaused = false;\n                this.comprehensionPaused = false;\n                this.resumePlaybackAfterTrainingPause = false;\n            }\n            this.updateTrainingTime();\n            const current = this.element('currentPos');\n"""))
repls.append((
"""            if (pause) {\n                pause.disabled = !active;\n                pause.textContent = snapshot.state === 'playing' ? '⏸' : (snapshot.state === 'manual' ? '▶' : '▶');\n                pause.title = snapshot.state === 'manual' ? '继续' : (snapshot.state === 'playing' ? '暂停' : '继续');\n            }\n""",
"""            if (pause) {\n                pause.disabled = !active;\n                pause.textContent = this.trainingPaused ? '▶' : '⏸';\n                pause.title = this.trainingPaused ? '继续训练（恢复计时）' : '暂停训练（暂停计时）';\n                pause.setAttribute?.('aria-label', pause.title);\n            }\n"""))
repls.append((
"""            this.element('speedReadingPrev')?.addEventListener('click', () => this.previousFrame());\n""",
"""            for (const id of ['focusModeDisplay', 'pageModeDisplay']) {\n                this.element(id)?.addEventListener('click', (event) => {\n                    if (!this.isReaderActive() || !['playing', 'paused'].includes(this.playback.state)) return;\n                    event.preventDefault();\n                    event.stopImmediatePropagation();\n                    this.toggleComprehensionPause();\n                }, true);\n            }\n\n            this.element('speedReadingPrev')?.addEventListener('click', () => this.previousFrame());\n"""))

for old, new in repls:
    if old not in s:
        raise SystemExit('missing reader-speed replacement:\n' + old[:180])
    s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')

# Index: load clock before playback bridge/controller integration.
p = ROOT / 'index.html'
s = p.read_text(encoding='utf-8')
old = '    <script src="playback-controller.js"></script>\n    <script src="reader-speed-playback-ui.js"></script>'
new = '    <script src="playback-controller.js"></script>\n    <script src="training-session-clock.js"></script>\n    <script src="reader-speed-playback-ui.js"></script>'
if old not in s:
    raise SystemExit('index playback scripts not found')
s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')
